# Generated by Django 2.2 on 2019-11-10 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones_partidos', '0002_auto_20191110_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocionpartido',
            name='participante_1',
            field=models.ManyToManyField(blank=True, default=None, related_name='participante_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promocionpartido',
            name='participante_2',
            field=models.ManyToManyField(blank=True, default=None, related_name='participante_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promocionpartido',
            name='participante_3',
            field=models.ManyToManyField(blank=True, default=None, related_name='participante_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promocionpartido',
            name='participante_4',
            field=models.ManyToManyField(blank=True, default=None, related_name='participante_4', to=settings.AUTH_USER_MODEL),
        ),
    ]
