# Generated by Django 2.2 on 2019-11-10 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promociones_partidos', '0003_auto_20191110_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocionpartido',
            name='participante_1',
        ),
        migrations.RemoveField(
            model_name='promocionpartido',
            name='participante_2',
        ),
        migrations.RemoveField(
            model_name='promocionpartido',
            name='participante_3',
        ),
        migrations.RemoveField(
            model_name='promocionpartido',
            name='participante_4',
        ),
        migrations.AddField(
            model_name='promocionpartido',
            name='participantes',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
