# Generated by Django 2.2 on 2019-11-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones_partidos', '0004_auto_20191110_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocionpartido',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
