# Generated by Django 2.2 on 2019-11-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones_partidos', '0005_promocionpartido_cerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocionpartido',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
