# Generated by Django 2.2 on 2019-10-04 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pistas', '0003_auto_20190923_1459'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pista',
        ),
        migrations.AddField(
            model_name='reserva',
            name='pista',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pistas.Pista'),
            preserve_default=False,
        ),
    ]
