# Generated by Django 2.2 on 2019-11-15 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pistas', '0003_auto_20191115_1037'),
        ('reservas', '0002_reserva_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='horario_pista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pistas.HorarioPista'),
            preserve_default=False,
        ),
    ]
