# Generated by Django 2.2 on 2019-10-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20191004_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pistas.Pista'),
        ),
    ]
