# Generated by Django 2.2 on 2019-11-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('inicio_campeonato', models.DateTimeField()),
                ('fin_inscripciones', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('nivel', models.CharField(choices=[('B', 'Bajo'), ('M', 'Medio'), ('A', 'Alto')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pareja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.Campeonato')),
            ],
        ),
    ]
