# Generated by Django 2.2 on 2019-11-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0002_auto_20191106_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pareja',
            name='campeonato',
        ),
        migrations.AddField(
            model_name='pareja',
            name='normativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campeonatos.Normativa'),
        ),
    ]
