# Generated by Django 2.2 on 2019-11-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0004_auto_20191106_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pareja',
            name='normativa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='campeonatos.Normativa'),
        ),
    ]
