# Generated by Django 2.2 on 2019-11-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_usuario'),
        ('campeonatos', '0006_auto_20191112_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfrentamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_1_pareja_1', models.IntegerField(blank=True, default=None, null=True)),
                ('set_1_pareja_2', models.IntegerField(blank=True, default=None, null=True)),
                ('set_2_pareja_1', models.IntegerField(blank=True, default=None, null=True)),
                ('set_2_pareja_2', models.IntegerField(blank=True, default=None, null=True)),
                ('set_3_pareja_1', models.IntegerField(blank=True, default=None, null=True)),
                ('set_3_pareja_2', models.IntegerField(blank=True, default=None, null=True)),
                ('ganador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='campeonatos.Pareja')),
                ('pareja_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareja_1', to='campeonatos.Pareja')),
                ('pareja_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareja_2', to='campeonatos.Pareja')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Reserva')),
            ],
        ),
        migrations.CreateModel(
            name='AceptaEnfrentamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('acepta_pareja_1', models.BooleanField(default=False)),
                ('acepta_pareja_2', models.BooleanField(default=False)),
                ('enfrentamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.Enfrentamiento')),
            ],
        ),
    ]
