# Generated by Django 2.2 on 2019-11-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0007_aceptaenfrentamiento_enfrentamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='campeonato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campeonatos.Campeonato'),
            preserve_default=False,
        ),
    ]
