# Generated by Django 2.2 on 2019-11-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0008_grupo_campeonato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='campeonato',
        ),
    ]
