# Generated by Django 2.2 on 2019-11-13 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0009_remove_grupo_campeonato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfrentamiento',
            name='reserva',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.Reserva'),
        ),
    ]
