# Generated by Django 2.2 on 2019-11-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0010_auto_20191113_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pareja',
            name='grupo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='campeonatos.Grupo'),
        ),
        migrations.AlterField(
            model_name='pareja',
            name='normativa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='campeonatos.Normativa'),
        ),
    ]
