# Generated by Django 2.2 on 2019-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0011_auto_20191113_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfrentamiento',
            name='ronda',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
