# Generated by Django 2.2 on 2020-01-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0014_grupo_campeonato'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfrentamiento',
            name='acepto_pareja_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enfrentamiento',
            name='acepto_pareja_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enfrentamiento',
            name='fecha',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='AceptaEnfrentamiento',
        ),
    ]
