# Generated by Django 2.2 on 2020-01-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0016_auto_20200113_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfrentamiento',
            name='set_1_pareja_1',
            field=models.CharField(choices=[('0', 'No jugado'), ('1', 15), ('2', 30), ('3', 40), ('4', 'juego')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='enfrentamiento',
            name='set_1_pareja_2',
            field=models.CharField(choices=[('0', 'No jugado'), ('1', 15), ('2', 30), ('3', 40), ('4', 'juego')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='enfrentamiento',
            name='set_2_pareja_1',
            field=models.CharField(choices=[('0', 'No jugado'), ('1', 15), ('2', 30), ('3', 40), ('4', 'juego')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='enfrentamiento',
            name='set_2_pareja_2',
            field=models.CharField(choices=[('0', 'No jugado'), ('1', 15), ('2', 30), ('3', 40), ('4', 'juego')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='enfrentamiento',
            name='set_3_pareja_1',
            field=models.CharField(choices=[('0', 'No jugado'), ('1', 15), ('2', 30), ('3', 40), ('4', 'juego')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='enfrentamiento',
            name='set_3_pareja_2',
            field=models.CharField(choices=[('0', 'No jugado'), ('1', 15), ('2', 30), ('3', 40), ('4', 'juego')], default='0', max_length=1),
        ),
    ]
