# Generated by Django 2.2 on 2020-01-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0017_auto_20200114_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='pareja',
            name='puntuacion_clasificacion',
            field=models.IntegerField(default=0),
        ),
    ]
