# Generated by Django 2.2 on 2019-11-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cubierta', models.BooleanField(default=False)),
                ('pavimento', models.CharField(choices=[('RS', 'Resina sintética'), ('CA', 'Césped artificial'), ('HP', 'Hormigón poroso'), ('C', 'Cemento')], max_length=2)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
            ],
        ),
    ]
