# Generated by Django 2.2 on 2019-11-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pista',
            name='cubierta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pista',
            name='pavimento',
            field=models.CharField(choices=[('RS', 'Resina sintética'), ('CA', 'Césped artificial'), ('HP', 'Hormigón poroso'), ('C', 'Cemento')], default='C', max_length=2),
            preserve_default=False,
        ),
    ]
