# Generated by Django 2.2 on 2019-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pista',
            name='hora_apertura',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pista',
            name='hora_cierre',
            field=models.TimeField(),
        ),
    ]
