# Generated by Django 2.2 on 2019-11-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioPista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.DurationField()),
            ],
        ),
    ]
