# Generated by Django 2.2 on 2019-09-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pistas', '0002_auto_20190923_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pista',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
