# Generated by Django 2.2 on 2019-11-15 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pistas', '0002_horariopista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariopista',
            name='duracion',
        ),
        migrations.AddField(
            model_name='horariopista',
            name='hora_fin',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariopista',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariopista',
            name='pista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pistas.Pista'),
            preserve_default=False,
        ),
    ]
